### ISSUE TITLE
I cant run this

### ISSUE THREAD

**Issue by Luamnoxu** [atomfinger/john_resume_pkg#1]
C:\Users\Maxim\Desktop>pip install john-resume
Requirement already satisfied: john-resume in c:\python310\lib\site-packages (1.0.0)
Requirement already satisfied: requests in c:\python310\lib\site-packages (from john-resume) (2.28.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\python310\lib\site-packages (from requests->john-resume) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python310\lib\site-packages (from requests->john-resume) (3.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python310\lib\site-packages (from requests->john-resume) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in c:\python310\lib\site-packages (from requests->john-resume) (3.4)

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\Maxim\Desktop>python
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> john-resume
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'john' is not defined
>>> john-resume();
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'john' is not defined
>>> import john-resume
  File "<stdin>", line 1
    import john-resume
               ^
SyntaxError: invalid syntax
>>> johnresume()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'johnresume' is not defined
>>> john-resume()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'john' is not defined
>>>

please fix 👍

**Comment by zydra-zy** [comment]
have you tried restarting your toaster cooker [Here.](https://www.youtube.com/watch?v=z5jfgpNBShs)

**Comment by Luamnoxu** [comment]
@Zy-dra                  _**#################[](url)**_
